"""empty message

Revision ID: 1f2d0678a0df
Revises: 2881b987ba1a
Create Date: 2019-02-21 01:28:30.695555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2d0678a0df'
down_revision = '2881b987ba1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expires_at')
    # ### end Alembic commands ###
