"""empty message

Revision ID: 2881b987ba1a
Revises: 
Create Date: 2019-02-21 00:53:29.269722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2881b987ba1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=64), server_default='', nullable=False),
    sa.Column('email', sa.String(length=128), server_default='', nullable=False),
    sa.Column('password_hash', sa.String(length=64), server_default='', nullable=False),
    sa.Column('secret_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
